
export const DESTINATION_DATA_LOADING : string="DESTINATION_DATA_LOADING"
export const DESTINATION_DATA_SUCCESS :string="DESTINATION_DATA_SUCCESS"
export const DESTINATION_DATA_ERROR :string="DESTINATION_DATA_ERROR"


export const PAYMENT_DATA_SUCCESS :string="PAYMENT_DATA_SUCCESS"